baseURL = "https://fatihkoc.net"
title = "Fatih Koç"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
pagerSize = 20
pygmentsStyle = "github-dark"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
enableRobotsTXT = true

[params.googleTagManager]
#id =

[params]
author = "Fatih Koç"
description = "Fatih Koç personal website. Things about DevOps, CI/CD, IaC etc. Always looking for new challenges."
keywords = "DevOps Engineer,Kubernetes,AWS,Azure,GCP,Terraform,Infrastructure as Code,CI/CD,Site Reliability Engineering,Cloud Architecture"
info = ["DevOps Engineer"]
avatarURL = "images/fatih-koc.jpg"
dateFormat = "January 2, 2006"
since = 2022

rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []

[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'",
  "'unsafe-inline'",
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/",
  "https://www.googletagmanager.com"
]
prefetchsrc = ["'self'"]
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 1
url = "https://www.linkedin.com/in/fatihhkoc/"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 3
url = "https://github.com/fatihkc/"

[[params.social]]
name = "Upwork"
icon = "fa fa-2x fa-briefcase"
weight = 2
url = "https://www.upwork.com/freelancers/fatihkoc"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 4
url = "https://twitter.com/fatihkocnet/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 5
url = "https://fatihkoc.net/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"
contentDir = "content"
weight = 1

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Contact"
weight = 3
url = "contact/"

### Deploy ###

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "fatihkocnet"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://fatihkocnet-hugo?region=eu-central-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "ECWXB3G1RK67X"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
