# This is a basic workflow to help you get started with Actions
name: Update website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
    paths:
      - site
      - site/**
      - .github/workflows/site.yml
      - cypress

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: site # Run all commands in the site directory

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0 

      # Runs a single command using the runners shell
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Build
        run: hugo --minify # Build the website

      - name: Deploy to AWS S3
        run: hugo deploy --force --invalidateCDN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  tests:
    needs: build-deploy # Wait for the build-deploy job to finish
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: cypress/e2e # Run all commands in the cypress/e2e directory

    steps:

      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4